# Generated by Django 6.0.1 on 2026-01-19 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id_category', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='PointPlace',
            fields=[
                ('id_PVZ', models.IntegerField(primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producers',
            fields=[
                ('id_producer', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id_provider', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id_status', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='UnitMes',
            fields=[
                ('id_unit_mes', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='DataOrder',
            fields=[
                ('id_data', models.IntegerField(primary_key=True, serialize=False)),
                ('date_order', models.DateField()),
                ('date_delivery', models.DateField()),
                ('code', models.IntegerField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_PVZ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBOM.pointplace')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBOM.statusorder')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_product', models.IntegerField(primary_key=True, serialize=False)),
                ('article', models.CharField()),
                ('name', models.CharField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.CharField()),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBOM.categoryproduct')),
                ('id_producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBOM.producers')),
                ('id_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBOM.providers')),
                ('id_unit_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBOM.unitmes')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('id_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBOM.dataorder')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBOM.products')),
            ],
        ),
    ]
